// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// sampler
Rcpp::NumericMatrix sampler(Rcpp::NumericVector y, Rcpp::NumericVector mu0, Rcpp::NumericVector tau20, Rcpp::NumericVector sigma20, Rcpp::NumericVector v0, double a, double b, int S = 1000, int B = 1000);
RcppExport SEXP bm_sampler(SEXP ySEXP, SEXP mu0SEXP, SEXP tau20SEXP, SEXP sigma20SEXP, SEXP v0SEXP, SEXP aSEXP, SEXP bSEXP, SEXP SSEXP, SEXP BSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP );
        Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mu0(mu0SEXP );
        Rcpp::traits::input_parameter< Rcpp::NumericVector >::type tau20(tau20SEXP );
        Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sigma20(sigma20SEXP );
        Rcpp::traits::input_parameter< Rcpp::NumericVector >::type v0(v0SEXP );
        Rcpp::traits::input_parameter< double >::type a(aSEXP );
        Rcpp::traits::input_parameter< double >::type b(bSEXP );
        Rcpp::traits::input_parameter< int >::type S(SSEXP );
        Rcpp::traits::input_parameter< int >::type B(BSEXP );
        Rcpp::NumericMatrix __result = sampler(y, mu0, tau20, sigma20, v0, a, b, S, B);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
