# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sampler <- function(y, mu0, tau20, sigma20, v0, a, b, S = 1000L, B = 1000L) {
    .Call('bm_sampler', PACKAGE = 'bm', y, mu0, tau20, sigma20, v0, a, b, S, B)
}

